cmake_minimum_required(VERSION 3.27)

include_guard()

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_SYSTEM_NAME Xbox)
set(CMAKE_CROSSCOMPILING 1)
set(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS OFF)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS OFF)

if(NOT DEFINED CMAKE_BUILD_TYPE OR CMAKE_BUILD_TYPE STREQUAL "")
	set(CMAKE_BUILD_TYPE "Debug")
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	set(DEBUG TRUE)
endif()

set(XDK_DIR              $ENV{XDK})
set(XDK_BIN_DIR          ${XDK_DIR}\\xbox\\bin)
set(XDK_VC_DIR           ${XDK_BIN_DIR}\\vc71)
set(XDK_INCLUDE_DIR      ${XDK_DIR}\\xbox\\include)
set(XDK_LIB_DIR          ${XDK_DIR}\\xbox\\lib)

set(CMAKE_C_COMPILER     ${XDK_VC_DIR}\\cl.exe)
set(CMAKE_CXX_COMPILER   ${XDK_VC_DIR}\\cl.exe)
set(CMAKE_CUSTOM_LINKER  ${XDK_VC_DIR}\\link.exe)
set(CMAKE_FIND_ROOT_PATH ${XDK_DIR})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)

set(CMAKE_MODULE_PATH                  ${CMAKE_CURRENT_LIST_DIR})
set(CMAKE_USER_MAKE_RULES_OVERRIDE_C   ${CMAKE_CURRENT_LIST_DIR}/Platform/Xbox-MSVC.cmake)
set(CMAKE_USER_MAKE_RULES_OVERRIDE_CXX ${CMAKE_CURRENT_LIST_DIR}/Platform/Xbox-MSVC.cmake)

set(CMAKE_C_FLAGS_INIT                  "")
set(CMAKE_C_FLAGS_DEBUG_INIT            "")
set(CMAKE_CXX_FLAGS_INIT                "")
set(CMAKE_CXX_FLAGS_DEBUG_INIT          "")
set(CMAKE_EXE_LINKER_FLAGS_INIT         "")
set(CMAKE_C_STANDARD_LIBRARIES          "")
set(CMAKE_CXX_STANDARD_LIBRARIES        "")
set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "")
set(CMAKE_MSVC_RUNTIME_LIBRARY          "")
set(CMAKE_MSVC_RUNTIME_CHECKS           "")

if(DEBUG)
	set(CMAKE_C_FLAGS          "/arch:SSE /EHsc /RTC1 /nologo /MTd /Od")
	set(CMAKE_CXX_FLAGS        "/arch:SSE /EHsc /RTC1 /nologo /MTd /Od")
	set(CMAKE_EXE_LINKER_FLAGS "/INCREMENTAL /NOLOGO /subsystem:xbox /MACHINE:I386 /DEBUG")
else()
	set(CMAKE_C_FLAGS          "/arch:SSE /EHsc /RTC1 /nologo /MT /O2")
	set(CMAKE_CXX_FLAGS        "/arch:SSE /EHsc /RTC1 /nologo /MT /O2")
	set(CMAKE_EXE_LINKER_FLAGS "/INCREMENTAL /NOLOGO /subsystem:xbox /MACHINE:I386")
endif()

#if(DEBUG)
#	set(CMAKE_EXE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS} /DEBUG)
#endif()

include_directories(SYSTEM ${XDK_INCLUDE_DIR})
link_directories(${XDK_LIB_DIR})
link_libraries(xboxkrnl.lib)
add_compile_definitions(_XBOX _MBCS _MSC_VER=1300)
if(DEBUG)
	add_compile_definitions(_DEBUG)
	link_libraries(xbdm.lib)
endif()

set(CMAKE_SYSTEM_PROCESSOR X86)

set(WIN32 TRUE)
set(MSVC TRUE)
set(XBOX TRUE)
